name: Mirroring armv7 Contaminated Debian Packages

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
  schedule:
    # Run daily at midnight
    - cron:  '0 0 * * *'

env:
  QT5_DEB_VERSION: "5.15.2+dfsg-3"
  DEB_ARCH: "armhf"
  PACKAGECLOUD_REPO: "experimental"
  OS: "debian"
  DISTRO: "bullseye"

jobs:
  build-debian-package:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        package: ["libqt5webengine5", "libqt5webenginecore5", "libqt5webenginewidgets5", "qml-module-qtwebengine"]

    steps:
      - run: wget http://ftp.de.debian.org/debian/pool/main/q/qtwebengine-opensource-src/${{ matrix.package }}_${{ env.QT5_DEB_VERSION }}_${{ env.DEB_ARCH }}.deb

      - uses: docker://lpenz/ghaction-packagecloud:v0.3
        with:
          repository: ${{ env.PACKAGECLOUD_REPO }}/${{ env.OS }}/${{ env.DISTRO }}
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
          files: ${{ matrix.package }}_${{ env.QT5_DEB_VERSION }}_${{ env.DEB_ARCH }}.deb
