name: Debian Packaging for Python Packages from PyPI

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/pypi-deb-build.yml"
      - "pypi-build/scripts"
      - "pypi-build/patches"

env:
  DEB_BUILD_DOCKER_IMAGE: "pitop/pi-top-os-deb-build"
  DEB_BUILD_DOCKER_TAG: "bullseye-master"
  CHANGELOG_AUTHOR_NAME: "pi-top"
  CHANGELOG_AUTHOR_EMAIL: "deb-maintainers@pi-top.com"
  PACKAGECLOUD_REPO: "experimental"
  OS: "debian"
  DISTRO: "bullseye"

jobs:
  build-debian-package:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # Default to host architecture for packages which do not require cross-compilation for ARM
        docker_architecture: ["linux/amd64"]

        # matrix.package[0] => name
        # matrix.package[1] => architecture(s)
        # matrix.package[2] => build dependencies
        # matrix.package[3] => options
        #   sdist_dsc_options:
        #     https://github.com/astraw/stdeb#stdeb-distutils-command-options
        #     https://github.com/astraw/stdeb#stdebcfg-configuration-file
        package:
          - ["click-logging", "", ""]
          - ["imutils", "", ""]
          - ["async-timeout", "", ""]
          - ["charset-normalizer", "", ""]
          - [
              "python-osc",
              "--package3 python3-osc",
              ""
            ]
          - [
              "python-sonic",
              "--package3 python3-sonic --depends3 python3-osc",
              ""
            ]
          - [
              "aiosignal",
              "--depends3 'python3-frozenlist (>=1.1.0)'",
              ""
            ]
         include:
          # Define packages which require cross-compilation here with ARM architectures
          - package: [
              "dlib",
              "",
              "build-essential cmake libopenblas-dev liblapack-dev libx11-dev libgtk-3-dev"
            ]
            docker_architecture: ["linux/arm/v7", "linux/arm64"]

          - package: ["frozenlist", "", ""]
            docker_architecture: ["linux/arm/v7", "linux/arm64"]

          - package: [
              "aiohttp",
              "--depends3 'python3-aiosignal (>= 1.1.2), python3-async-timeout (>= 4.0.0), python3-frozenlist(>= 1.1.1), python3-charset-normalizer (>= 2.0), python3-charset-normalizer (< 4), python3-multidict (>=4.5), python3-multidict(< 7), python3-yarl(>=1.0), python3-yarl (< 2), python3-typing-extensions (>= 3.7.4)'",
              ""
            ]
            docker_architecture: ["linux/arm/v7", "linux/arm64"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0

      - name: Build in ARM Docker container
        run: |
          docker run --rm --privileged tonistiigi/binfmt --install all

          docker run -i \
            --volume ${{ github.workspace }}:${{ github.workspace }} \
            --workdir=${{ github.workspace }} \
            -e BUILD_DEPENDENCIES="${{ matrix.package[2] }}" \
            --platform ${{ matrix.docker_architecture }} \
            pitop/pypi-build:latest \
            bash -c "sudo apt update && \
            ./pypi-build/scripts/pypi-build.py ${{ matrix.package[0] }} \
              --options-str=\"${{ matrix.package[3] }} --upstream-version-suffix '+ptos3' --debian-version ${{ github.run_number }}\" "

      - name: Generate artifact name
        run: |
          echo "ARTIFACT_PREFIX=$(basename -s .dsc "$(find . -name "*.dsc")")" >> $GITHUB_ENV

      - name: Upload binary package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_PREFIX }}.deb
          path: ./artifacts/*.deb

      - name: Upload source package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_PREFIX }}.deb-src
          path: ./artifacts/*.tar.xz

      - name: Upload package build metadata artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_PREFIX }}.metadata
          path: |
            ./artifacts/**
            !./artifacts/*.deb
            !./artifacts/*.tar.xz

      - uses: pi-top/ghaction-packagecloud@main
        if: github.ref == 'refs/heads/master'
        with:
          repository: ${{ env.PACKAGECLOUD_REPO }}/${{ env.OS }}/${{ env.DISTRO }}
          files: |
            ./artifacts/*.dsc
            ./artifacts/*.deb
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
